version: "3"

services:
  apisix:
    image: apache/apisix:3.8.0-debian
    platform: linux/amd64
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_plugins:/opt/apisix/plugins:ro
    restart: always
    ports:
      - "9080:9080"
      - "9180:9180"
    depends_on:
      - etcd
  etcd:
    image: bitnami/etcd:3.5.12
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2397"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2397"
  chopshop-backend:
    image: chopshop-backend:1.2
    environment:
      SPRING_R2DBC_URL: "r2dbc:mariadb://mariadb:3306/chopshop"
      SPRING_DEVTOOLS_ADD-PROPERTIES: false
    depends_on:
      - mariadb
  chopshop-frontend:
    build: chop-shop-frontend
    environment:
      API_URL: http://localhost:9080/api
    depends_on:
      - chopshop-backend
  mariadb:
    image: mariadb:11.3.2
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "chopshop"
    volumes:
      - ./chop-shop/sql:/docker-entrypoint-initdb.d:ro
