version: "3"

services:
  apisix:
    image: apache/apisix:2.13.1-alpine
    command: sh -c "/opt/util/wait-for etcd:2397 -- /usr/bin/apisix init && /usr/bin/apisix init_etcd && /usr/local/openresty/bin/openresty -p /usr/local/apisix -g 'daemon off;'"
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./util:/opt/util:ro
    ports:
      - "9080:9080"
      - "9091:9091"
      - "9443:9443"
      - "9092:9092"
    depends_on:
      - etcd
  etcd:
    image: bitnami/etcd:3.5.2
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2397"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2397"
    ports:
      - "2397:2397"
  chopshop:
    image: chopshop:1.3
    environment:
      SPRING_R2DBC_URL: "r2dbc:mariadb://mariadb:3306/chopshop"
      SPRING_DEVTOOLS_ADD-PROPERTIES: false
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10-focal
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "chopshop"
    volumes:
      - ./chop-shop/sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
